#################################
# spring ai
#################################
# spring.ai.openai.api-key=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
# spring.ai.openai.chat.model=gpt-3.5-turbo
spring.ai.chat.client.enabled=false
#################################

#################################
# readit
#################################
# VertexAI Credential
vertex.ai.gemini.credentials-uri=c:/Users/Public/FDX/Config/fdxchatgpt-googleocr-calcium-hope-397308-aff1db1db504.json
vertex.ai.gemini.project-id=calcium-hope-397308
vertex.ai.gemini.location=asia-southeast1
#################################
# default Vector Service
vector-service-id=qdrantCloud
#################################
# default LLM Service
llm-service-id=openAI40oMini
llm-model-id=gpt-4o-mini
#################################
# default Embedding Service
emb-service-id=openAI_text-embedding-3-small
emb-model-id=text-embedding-3-small
#################################
# chunking delimiter
chunker.delimiters=".!?\n"
#################################
# default File Upload Path
fileUploadPath=/uploads/temp/
#################################
# marker API
markerApiBaseUrl=http://fdx.iptime.org:52970
markerApiUri=/marker_convert
markerApiTimeoutSecond=100
#################################
# Pymupdf4llm API
pymupdf4llmApiUri=/pymupdf4llm_convert
#################################



#################################
# Qdrant - Local
#################################
#vectorstore.qdrant.host=localhost
#vectorstore.qdrant.port=6333
#vectorstore.qdrant.useTls=false
#vectorstore.qdrant.api-key=
#vectorstore.qdrant.collection-name=공무원휴가제도
#################################
# Qdrant - Cloud
#################################
vectorstore.qdrant.host=663ac521-23a3-4289-ade7-90803720720b.us-east4-0.gcp.cloud.qdrant.io
vectorstore.qdrant.port=6334
vectorstore.qdrant.useTls=true
vectorstore.qdrant.api-key=ARNJap1mmrRKOWRcssUOkDFaE6QCXaDWYgmwFxbuUGLip5AwvGdugg
vectorstore.qdrant.collection-name=공무원휴가제도
#################################
